### ISSUE TITLE
avn does not handle release names

### ISSUE THREAD

**Issue by apolishch** [wbyoung/avn#56] opened 2017-04-28 12:15 UTC
Please describe your issue clearly and also include all details below.
It is possibly to have a .nvmrc point at (for example lts/boron) This is currently not supported by avn.
**Details**

_avn --version: 0.2.3
node --version: nvm is working (without avn) so this kinda depends
nvm --version: 0..33.2
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
Copyright (C) 2007 Free Software Foundation, Inc.

My directory does not have a .node_version file, uses .nvmrc. But the output of __avn_debug is:

```sh
avn could not activate node lts/boron
error: no plugin passed predicate
  avn-nvm: no version matching lts/boron
  avn-n: no version matching lts/boron
```

`avn` is loaded in my `~/.bash_profile` file with:

- [ x] As an `nvm` user I am confirming that I did _not_ install with Homebrew

**Comment by wbyoung** [comment] 2017-04-28 14:07
Duplicate of #43.

**Closed by wbyoung** 2017-04-28 14:07 UTC
