### ISSUE TITLE
avn-nvm does not like .nvmrc to be system

### ISSUE THREAD

**Issue by srl295** [wbyoung/avn#53] opened 2017-02-21 18:23 UTC
Please describe your issue clearly and also include all details below.

**Details**

```
0.2.3
v7.4.0
0.31.1
GNU bash, versi'on 4.4.5(1)-release (x86_64-apple-darwin16.3.0)
```

`avn` is loaded in my `~/.{bash|zsh}{_profile|rc}` file with:

`~/.profile.d/extensions/avn` as in [here](https://github.com/srl295/.profile.d/blob/master/extensions/avn) 

**nvm specific**

- [X] As an `nvm` user I am confirming that I did _not_ install with Homebrew

-----

`avn-nvm` does not like having `system` in my `~/.nvmrc`, it is [specifically excluded](https://github.com/wbyoung/avn-nvm/blob/master/index.js#L58)  Is there another way to make `system` my default?  I don’t want an nvm-managed node to be default, just to fall back to `nvm use system` when not in a `.node-version` controlled directory.

**Comment by wbyoung** [comment] 2017-03-04 02:20
This is a duplicate of #43. PR welcome!

**Closed by wbyoung** 2017-03-04 02:20 UTC
