### ISSUE TITLE
avn could not activate node v4.0.0

### ISSUE THREAD

**Issue by AlexeyPopov** [wbyoung/avn#25] opened 2015-09-12 12:00 UTC
```
$ cat .node-version
v4.0.0

------

$ _avn explain -v
error: missing required argument `path'

------

$ nvm --version
0.26.1

------

$ nvm list
    iojs-v1.2.0
    iojs-v2.3.0
    iojs-v2.3.1
    iojs-v2.3.3
    iojs-v2.3.4
    iojs-v2.4.0
->  iojs-v2.5.0
         v4.0.0
default -> stable (-> v4.0.0)
node -> stable (-> v4.0.0) (default)
stable -> 4.0 (-> v4.0.0) (default)
iojs -> iojs-v2.5 (-> iojs-v2.5.0) (default)

------

$ node -v
v2.5.0
```

**Comment by wbyoung** [comment] 2015-09-12 15:09
What do you get for `_avn --version`?

If you're not on 0.2.2, can you update:

```bash
npm i -g avn
avn setup
```

If you're still having issues, can you try this debug command: `__avn_debug`.

It's working fine for me:

```bash
$ cat .node-version
v4.0.0

$ __avn_debug 
avn activated v4.0.0 (avn-nvm v4.0.0)
nvm use v4.0.0 > /dev/null;

$ nvm --version
0.26.1

$ nvm list
    iojs-v1.1.0
        v0.7.12
        v0.8.26
        v0.9.12
       v0.10.26
       v0.10.28
       v0.10.32
       v0.10.36
       v0.10.38
       v0.11.11
       v0.11.12
       v0.11.13
       v0.11.14
        v0.12.0
        v0.12.2
->       v4.0.0
         system
0.10 -> 0.10.26 (-> v0.10.26)
default -> stable (-> v4.0.0)
node -> stable (-> v4.0.0) (default)
stable -> 4.0 (-> v4.0.0) (default)
unstable -> 0.11 (-> v0.11.14) (default)
iojs -> iojs-v1.1 (-> iojs-v1.1.0) (default)

$ node -v
v4.0.0
```

**Comment by wbyoung** [comment] 2015-09-12 16:33
Oh, you should probably update `avn-nvm

**Comment by AlexeyPopov** [comment] 2015-09-12 16:41
There is my debug info.
```
$ _avn --version
0.2.2

$ __avn_debug
avn could not activate node v4.0.0
error: no plugin passed predicate
  avn-nvm: nvm exited with status: 127
bash: /Users/alexey/.nvm/nvm.sh: No such file or directory
bash: nvm: command not found
  avn-n: no version matching v4.0.0
```

**Comment by AlexeyPopov** [comment] 2015-09-12 16:42
```
$ nvm --version
0.26.1
```

**Comment by wbyoung** [comment] 2015-09-12 16:44
What shell are you using & where is `nvm` installed if it doesn't exist at `~/.nvm`? What does your profile script do to set up `nvm`?

Can you also post your `env`?

**Comment by AlexeyPopov** [comment] 2015-09-12 16:52
I install nvm via homebrew. I found my error. I copy nvm.sh in .nvm folder and the problem was resolved.

```
cp $(brew --prefix nvm)/nvm.sh ~/.nvm/
```

**Comment by wbyoung** [comment] 2015-09-12 16:58
The `nvm` team doesn't really support homebrew at this time and I seem to remember others with similar issues by installing with homebrew and then using `avn`.

See creationix/nvm#469.

**Comment by ljharb** [comment] 2015-09-13 04:05
@AlexeyPopov yes, please do **not** install `nvm` with homebrew. It does a poor job and is utterly unsupported.

**Comment by MPV** [comment] 2015-11-25 15:02
I'd like us to reopen this issue. 

I've got the same issue, but I haven't installed `nvm` with Homebrew (I used the recommended way from their readme). 

I just installed them all (`nvm`, `avn`), so I seem to have all the latest versions:

```
$ avn --version
0.2.2

$ nvm --version
0.29.0

$ nvm ls
         v4.2.1
->       system
node -> stable (-> v4.2.1) (default)
stable -> 4.2 (-> v4.2.1) (default)
iojs -> N/A (default)
```

Here's my debug output:
```
$ __avn_debug 
avn could not activate node v4.2.1
error: no plugin passed predicate
```

**Comment by wbyoung** [comment] 2015-11-25 21:41
@MPV did you `npm i -g avn-nvm` before `avn setup`?

What does `ls ~/.avn/plugins` show?

**Comment by MPV** [comment] 2015-11-30 09:50
Yes, I installed both `avn` and `avn-nvm` before `avn setup`. 

Also tried it again, which doesn't appear to change anything:

```
$ npm i -g avn-nvm
/usr/local/lib
├── UNMET PEER DEPENDENCY avn@0.2.x
└── avn-nvm@0.2.1 

npm WARN EPEERINVALID avn-nvm@0.2.1 requires a peer of avn@0.2.x but none was installed.

$ avn setup
avn: profile already set up (~/.zshrc)
avn: profile already set up (~/.bash_profile)
avn: configuration unchanged (~/.avnrc)
```

But the plugins folder is empty (I suppose it shouldn't be?)

```
$ ls -lah ~/.avn/plugins
total 0
drwxr-xr-x   3 vs  staff   102B 25 Nov 15:57 .
drwxr-xr-x  19 vs  staff   646B 25 Nov 15:57 ..
-rw-r--r--   1 vs  staff     0B 25 Nov 15:57 .keep
```

**Comment by wbyoung** [comment] 2015-12-01 04:46
@MPV okay. The `UNMET PEER DEPENDENCY` seems to indicate that `avn` is not installed for the version of `node`/`npm` that you installed `avn-nvm` for. Please try the [full install](https://github.com/wbyoung/avn#install) all at once in the same shell:

```bash
npm i -g avn avn-nvm
avn setup

# re-check installed plugins now
ls -la ~/.avn/plugins
```

**Comment by MPV** [comment] 2015-12-02 17:20
I might misunderstand, but looks to me like I have both?

```
$ npm ls -g | grep avn
├─┬ avn@0.2.2
├─┬ avn-nvm@0.2.1
```

I have tried uninstalling and (re)installing it now:

```
$ npm i -g avn avn-nvm
/usr/local/bin/avn -> /usr/local/lib/node_modules/avn/bin-public/avn
/usr/local/lib
├─┬ avn@0.2.2 
[...]

$ avn setup
avn: profile already set up (~/.bash_profile)
avn: profile already set up (~/.zshrc)
avn: configuration unchanged (~/.avnrc)

$ cd my_project
avn could not activate node v4.2.1

$ __avn_debug 
avn could not activate node v4.2.1
error: no plugin passed predicate

$ ls -lah ~/.avn/plugins
total 0
drwxr-xr-x   3 vs  staff   102B 25 Nov 15:57 .
drwxr-xr-x  19 vs  staff   646B 25 Nov 15:57 ..
-rw-r--r--   1 vs  staff     0B 25 Nov 15:57 .keep
```

I also tried removing the configs and running `avn setup` again:
```
$ rm -rf ~/.avn*

$ avn setup
avn: profile already set up (~/.bash_profile)
avn: profile already set up (~/.zshrc)
avn: configuration complete (~/.avnrc)
avn: installation complete

$ cd my_project
avn could not activate node v4.2.1

$ ls -lah ~/.avn/plugins
total 0
drwxr-xr-x   3 vs  staff   102B  2 Dec 18:18 .
drwxr-xr-x  19 vs  staff   646B  2 Dec 18:18 ..
-rw-r--r--   1 vs  staff     0B  2 Dec 18:18 .keep
```

**Comment by wbyoung** [comment] 2015-12-02 18:16
What version of `node` and `npm` are you using? What shell and on which OS?

Can you clone the project and run `npm install; npm test` and see if the tests pass in your environment?

**Comment by MPV** [comment] 2015-12-03 16:31
```
$ node -v
v4.1.1

$ npm -v
3.3.9
```

I've run the tests in the `~/.avn` folder. I will also try later to clone+install+test as well (if that's different).

**Comment by wbyoung** [comment] 2015-12-04 06:05
This all works completely fine on Mac OS X 10.11 (x86_64-apple-darwin15) with `bash` 3.2.57:

```console
$ node --version
v4.0.0
$ nvm install 4.1.1
######################################################################## 100.0%
Checksums empty
Now using node v4.1.1 (npm v2.14.4)
$ npm i -g npm@3.3.9 &>/dev/null
$ node --version
v4.1.1
$ npm --version
3.3.9
$ ls ~/.avn
ls: /Users/wbyoung/.avn: No such file or directory
$ npm i -g avn avn-nvm &>/dev/null
$ avn setup
avn: profile already set up (~/.bash_profile)
avn: profile already set up (~/.zshrc)
avn: configuration unchanged (~/.avnrc)
avn: installation complete
avn-nvm: installation complete
$ ls ~/.avn/plugins
avn-nvm
```

It also works with `zsh` 5.0.7 and robbyrussell/oh-my-zsh@c82f49e:

```console
➜  ~  nvm uninstall 4.1.1
Uninstalled node v4.1.1
➜  ~  node --version
v4.0.0
➜  ~
➜  ~  nvm install 4.1.1
######################################################################## 100.0%
Checksums empty
Now using node v4.1.1 (npm v2.14.4)
➜  ~  npm i -g npm@3.3.9 &>/dev/null
➜  ~  node --version
v4.1.1
➜  ~  npm --version
3.3.9
➜  ~  npm i -g npm@3.3.9 &>/dev/null
➜  ~  node --version
v4.1.1
➜  ~  npm --version
3.3.9
➜  ~  ls ~/.avn
ls: /Users/wbyoung/.avn: No such file or directory
➜  ~  npm i -g avn avn-nvm &>/dev/null
➜  ~  avn setup
avn: profile already set up (~/.bash_profile)
avn: profile setup complete (~/.zshrc)
avn: restart your terminal to start using avn
avn: configuration unchanged (~/.avnrc)
avn: installation complete
avn-nvm: installation complete
➜  ~  ls ~/.avn/plugins
avn-nvm
```

Perhaps you should completely remove your node install and try setting up everything again?

```bash
nvm install 4.0
nvm uninstall 4.1.1
nvm install 4.1.1
npm i -g npm@3.3.9
npm i -g avn avn-nvm
avn setup
```

I'm not sure I can give much more help here. I think there's probably a configuration problem somewhere in what you have set up, and I don't think that I'll be able to find it.

Also, as the original poster's issue was solved here, I'm going to close this issue now, but you can open a new one, @MPV, if you have more details to share on what you believe the issue is. Please include your OS version and versions of `zsh` and `oh-my-zsh` that you're using. Also, please try disabling any `oh-my-zsh` plugins that you may have and please follow the instructions above after everything is disabled. Lastly, please report what happens when you try these same things with `bash` on your machine. Please include all of those details in the new issue and link to this one as well. Without it, I'm not sure we'll make any more progress.

**Closed by wbyoung** 2015-12-04 06:05 UTC

**Comment by jonaslu** [comment] 2017-05-24 08:02
I'd just thought I'd add here if someone runs into this they will probably wind up here searching for a solution. I installed nvm via the arch-linux aur repositories (https://aur.archlinux.org/packages/nvm/) and got the same
```bash
avn could not activate node 4.8.0
```
Running the following showed:
```bash
$ __avn_debug                                                 
avn could not activate node 4.8.0                               
error: no plugin passed predicate                          
  avn-nvm: nvm exited with status: 127               
/bin/bash: /home/jonasl/.nvm/nvm.sh: No such file or directory
/bin/bash: nvm: command not found                
```
The fix was a simple:
```bash
$ ln -s /usr/share/nvm/nvm.sh ~/.nvm/nvm.sh
```

**Comment by ljharb** [comment] 2017-05-24 16:28
Does aur install nvm to a non-user-specific location? Where can I file an issue about that?

**Comment by jonaslu** [comment] 2017-05-25 14:39
Well, theres a pretty dense page about how to report bugs - (never filed a bug against a package myself): https://wiki.archlinux.org/index.php/Reporting_bug_guidelines

**Comment by ljharb** [comment] 2017-06-01 06:42
Thanks, I've posted a comment on the AUR page directly.
