### ISSUE TITLE
Why not use package.json `engine`?

### ISSUE THREAD

**Issue by rstacruz** [wbyoung/avn#39] opened 2016-02-02 03:40 UTC
`.node-version` seems like a throwback at `.ruby-version`. There's no need to copy them, though... package.json already has an `engine` field which defines what node version you want to use.

**Comment by wbyoung** [comment] 2016-02-02 04:14
Duplicate of #10. Please read the discussion and weigh in there.

**Closed by wbyoung** 2016-02-02 04:14 UTC
