### ISSUE TITLE
Creating new terminal sessions doesn't keep node version in sync

### ISSUE THREAD

**Issue by milanlandaverde** [wbyoung/avn#8] opened 2015-02-12 16:10 UTC
In running multiple build tasks, I open up different terminal sessions and want to have avn keep using the same node version I was using in previous terminal sessions. Otherwise I have to run `cd .` every time I open up a new session and want to switch to the correct node version that the directory specified. I'm using iTerm2 and zsh.

**Comment by wbyoung** [comment] 2015-02-12 16:38
@milanlandaverde does iTerm2 have the ability to keep environment variables set when starting new sessions?

**Comment by milanlandaverde** [comment] 2015-02-13 03:26
I'm not sure I understand. Do you mean env vars that were set in the previous session?

This problem also seems to happening for me on Terminal with zsh.

**Comment by wbyoung** [comment] 2015-02-13 07:11
@milanlandaverde yes, environment variables that were set in the previous session, the one where you presumably `cd` to your project directory before getting started.

It's a problem with bash in Terminal.app as well because the environment variables are not copied over to new sessions there. I'm just checking to see if there's consistency between your setup and Terminal.app/bash.

With Terminal.app, I don't think it's actually using `cd` to get to the new working directory. But the same thing does seem to work with RVM in bash and Terminal.app, so I think it's something that can be addressed by avn.

**Comment by JackCA** [comment] 2015-04-06 01:57
I'm also looking for a way to do this (specifically with iTerm2 and zsh)... any workaround? I haven't found a simple way to preserve environment variables between sessions either

**Comment by wbyoung** [comment] 2015-04-06 22:28
@JackCA I've confirmed that with iTerm2 and zsh that RVM correctly configures the proper ruby version when starting a new session.

I have an iTerm profile configured with _Working Directory_ set to _Reuse previous session's directory_ and the _Command_ set to `/usr/local/bin/zsh` (a Homebrew install of zsh) rather than configuring my system shell to be zsh.

This at least indicates that it's possible for this to work, but I'll dig into this a bit more.

**Closed** 2015-04-06 22:54 UTC

**Comment by wbyoung** [comment] 2015-04-06 22:56
This should be fixed now. Please install version 0.1.7 and update your avn setup:

```bash
npm i -g avn
avn setup
```

**Comment by milanlandaverde** [comment] 2015-04-06 22:57
Schweet

**Comment by JackCA** [comment] 2015-04-06 22:59
awesome!!! Confirmed to be working :+1:

**Comment by wbyoung** [comment] 2015-04-06 23:00
@JackCA thanks for the confirmation!
