### ISSUE TITLE
AVN creates .bash_profile instead of writing in .profile

### ISSUE THREAD

**Issue by slorber** [wbyoung/avn#49] opened 2016-11-07 11:43 UTC
Hi,

My mac had a .profile config. After installing AVN a lot of my things in shell got broken, because AVN created a .bash-profile file that did not exist before.

This lead to my .profile not being loaded anymore, leading to my $PATH being incorrect, my aliases not being created.

I think AVN should append to .profile if it exists, because creating .bash_profile will make bash to not load .profile file, making other apps unusable in the same time

**Details**

- _avn_ `avn --version`: 0.2.3
- _node_ `node --version` 7.0.0
- _nvm_ `nvm --version` 0.32.1
- _n_ `n --version` not found
- _zsh_ `zsh --version` 5.0.8
- _bash_ `bash --version` 3.2.57(1)

**Comment by wbyoung** [comment] 2016-11-07 19:48
Duplicate of #31.

**Closed by wbyoung** 2016-11-07 19:48 UTC

**Comment by edsfocci** [comment] 2017-01-11 18:02
@slorber What version of Mac OS?

**Comment by slorber** [comment] 2017-01-12 11:49
I don't know it's probably 10.11.6 I didn't do any update for a while and it's my current version

**Comment by thooyork** [comment] 2019-10-16 20:39
Just copy the folowing line from ~/.bash_profile into ~/.bashrc if you're using linux.
[[ -s "$HOME/.avn/bin/avn.sh" ]] && source "$HOME/.avn/bin/avn.sh" # load avn
